version: '3'
services:
  web:
    build: .
    environment:
      - FLASK_RUN_HOST=0.0.0.0
    ports:
      - "5000:5000"
#  db:
#    image: "nginx:1.13.5"
#    ports:
#      - "8080:80"
#    volumes:
#      - ./conf.d:/etc/nginx/conf.d
#    depends_on:
#      - web